name: Автопул и деплой после merge в main

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Настроить SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Деплой на сервер
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "\
            cd ${{ secrets.SERVER_PATH }} && \
            git pull origin main && \
            source .venv/bin/activate && \
            pip install -r requirements.txt && \
            nohup streamlit run dashboard_app.py --server.address 0.0.0.0 --server.port 8501 &"
