name: Автопул и деплой после merge в main

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Настроить SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Проверка SSH-соединения
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} echo "SSH is working"

      - name: Деплой на сервер
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "\
            cd ${{ secrets.SERVER_PATH }} && \
            git pull origin main && \
            source .venv/bin/activate && \
            pip install -r requirements.txt && \
            nohup streamlit run dashboard_app.py --server.address 0.0.0.0 --server.port 8501 > streamlit.log 2>&1 &"
